In [13]:
import torch
import torch.nn as nn

# Introduction to Deep Learning in Python

## Creating tensors and accessing attributes

In [14]:
list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

print(tensor_a)

print(tensor_a.device)

print(tensor_a.dtype)

tensor([1, 2, 3, 4])
cpu
torch.int64


## Creating tensors from numpy arrays

In [15]:
array_a = [[1, 1, 1], [2, 3, 4], [4, 5, 6]]
array_b = [[7, 5, 4], [2, 2, 8], [6, 3, 8]]

tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

tensor_c = tensor_a - tensor_b

tensor_d = tensor_a * tensor_b

tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]])


# Creating our first neural network

## Yor first neural network

In [16]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

model = nn.Sequential(
  nn.Linear(8, 4),
  nn.Linear(4, 1)
)

output = model(input_tensor)
print(output)

tensor([[-1.3139]], grad_fn=<AddmmBackward0>)


# Using the sigmoig and softmax function

## Sigmoid function

In [17]:
score = torch.tensor([[0.8]])

sigmoid = nn.Sigmoid()
probability = sigmoid(score)
print(probability)

tensor([[0.6900]])


## Softmax function

In [18]:
scores = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

softmax = nn.Softmax(dim=-1)
probabilities = softmax(scores)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])
