# Running a forward pass

In [50]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## Building a binary classifier in PyTorch

In [51]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.1185]], grad_fn=<SigmoidBackward0>)


## From regression to multi-class classification

In [52]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.0673, 0.0211, 0.4520, 0.4596]], grad_fn=<SoftmaxBackward0>)


# Using loss functions to assess model predictions

## Creating one-hot encoded labels

In [53]:
y = 1
num_classes = 3

one_hot_numpy = np.array([0, 1, 0])

one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes = num_classes)

print(one_hot_pytorch)

tensor([0, 1, 0])


## Calculating cross entropy loss

In [54]:
y = [2]
scores = torch.Tensor([[0.1, 6.0, -2.0, 3.2]])

one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])
print(one_hot_label)

criterion = nn.CrossEntropyLoss()

loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor([[0, 0, 1, 0]])
tensor(8.0619, dtype=torch.float64)


# Using derivatives to update model parameters

## Estimating a sample

In [55]:
sample = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])
target = F.one_hot(torch.tensor([2]), 4).double()

model = nn.Sequential(
  nn.Linear(11, 8),
  nn.Linear(8, 6),
  nn.Linear(6, 4)
)

prediction = model(sample)

criterion = nn.CrossEntropyLoss()
loss = criterion(prediction, target)
loss.backward()

print(model[0].weight.grad)
print(model[0].bias.grad)

print(model[1].weight.grad)
print(model[1].bias.grad)

print(model[2].weight.grad) 
print(model[2].bias.grad) 

tensor([[-0.0544, -0.0725, -0.1088, -0.1269, -0.1814, -0.2176, -0.0363, -0.0544,
         -0.1088, -0.1451, -0.1632],
        [ 0.0600,  0.0799,  0.1199,  0.1399,  0.1999,  0.2398,  0.0400,  0.0600,
          0.1199,  0.1599,  0.1799],
        [ 0.0817,  0.1089,  0.1633,  0.1906,  0.2722,  0.3267,  0.0544,  0.0817,
          0.1633,  0.2178,  0.2450],
        [-0.0058, -0.0077, -0.0116, -0.0135, -0.0193, -0.0232, -0.0039, -0.0058,
         -0.0116, -0.0155, -0.0174],
        [ 0.0068,  0.0091,  0.0136,  0.0159,  0.0227,  0.0272,  0.0045,  0.0068,
          0.0136,  0.0182,  0.0204],
        [ 0.0260,  0.0346,  0.0519,  0.0606,  0.0866,  0.1039,  0.0173,  0.0260,
          0.0519,  0.0693,  0.0779],
        [ 0.0319,  0.0425,  0.0638,  0.0744,  0.1064,  0.1276,  0.0213,  0.0319,
          0.0638,  0.0851,  0.0957],
        [-0.0442, -0.0590, -0.0885, -0.1032, -0.1475, -0.1770, -0.0295, -0.0442,
         -0.0885, -0.1180, -0.1327]])
tensor([-0.0181,  0.0200,  0.0272, -0.0019,  0.0023,  0

## Accessing the model parameters

In [56]:
model = nn.Sequential(
  nn.Linear(16, 8),
  nn.Sigmoid(),
  nn.Linear(8, 2))

weight_0 = model[0].weight

bias_1 = model[2].bias

## Updating the weights manually

In [57]:
sample = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])
target = F.one_hot(torch.tensor([2]), 4).double()

model = nn.Sequential(
  nn.Linear(11, 8),
  nn.Linear(8, 6),
  nn.Linear(6, 4)
)

prediction = model(sample)

criterion = nn.CrossEntropyLoss()
loss = criterion(prediction, target)
loss.backward()

weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

lr = 0.001

weight0 = weight0 - lr * grads0
weight1 = weight1 - lr * grads1
weight2 = weight2 - lr * grads2

print(weight0)
print(weight1)
print(weight2)

tensor([[-0.1142, -0.2652,  0.0361, -0.2031, -0.1615,  0.0458,  0.2113,  0.1753,
          0.0666,  0.0026,  0.0182],
        [ 0.0633,  0.0761,  0.2609, -0.0135,  0.2406,  0.1823, -0.1064, -0.2179,
         -0.0384,  0.0174, -0.0534],
        [ 0.0685,  0.0482,  0.2956,  0.0875,  0.2571, -0.2901, -0.0320, -0.2858,
          0.2202, -0.1376,  0.0757],
        [ 0.0025,  0.1906, -0.0160, -0.0039, -0.2458,  0.1176,  0.0619, -0.1256,
         -0.0352,  0.1972,  0.0676],
        [ 0.0610,  0.1847,  0.0978, -0.2638,  0.0666,  0.1897,  0.1581, -0.2218,
          0.1493, -0.0674, -0.1452],
        [-0.1145,  0.2745,  0.2853, -0.1747, -0.1758, -0.0903,  0.2731, -0.0406,
          0.0194,  0.0793, -0.2222],
        [-0.1546,  0.1802,  0.0311, -0.1750, -0.1461, -0.2675, -0.2764,  0.0827,
         -0.0815, -0.2837, -0.2068],
        [ 0.1601, -0.2550,  0.1258, -0.2115,  0.1603, -0.0755,  0.1136, -0.2030,
         -0.0019, -0.0849,  0.2582]], grad_fn=<SubBackward0>)
tensor([[ 0.0997,  0.1416, -0.3

## Using the PyTorch optimizer

In [58]:
optimizer = optim.SGD(model.parameters(), lr=0.001)

optimizer.step()