# Running a forward pass

In [27]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

## Building a binary classifier in PyTorch

In [28]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.6961]], grad_fn=<SigmoidBackward0>)


## From regression to multi-class classification

In [29]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.7459, 0.2000, 0.0068, 0.0474]], grad_fn=<SoftmaxBackward0>)


# Using loss functions to assess model predictions

## Creating one-hot encoded labels

In [30]:
y = 1
num_classes = 3

one_hot_numpy = np.array([0, 1, 0])

one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes = num_classes)

print(one_hot_pytorch)

tensor([0, 1, 0])


## Calculating cross entropy loss

In [31]:
y = [2]
scores = torch.Tensor([[0.1, 6.0, -2.0, 3.2]])

one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])
print(one_hot_label)

criterion = nn.CrossEntropyLoss()

loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor([[0, 0, 1, 0]])
tensor(8.0619, dtype=torch.float64)


# Using derivatives to update model parameters

## Estimating a sample

In [32]:
sample = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])
target = F.one_hot(torch.tensor([2]), 4).double()

model = nn.Sequential(
  nn.Linear(11, 8),
  nn.Linear(8, 6),
  nn.Linear(6, 4)
)

prediction = model(sample)

criterion = nn.CrossEntropyLoss()
loss = criterion(prediction, target)
loss.backward()

print(model[0].weight.grad)
print(model[0].bias.grad)

print(model[1].weight.grad)
print(model[1].bias.grad)

print(model[2].weight.grad) 
print(model[2].bias.grad) 

tensor([[-0.0229, -0.0306, -0.0458, -0.0535, -0.0764, -0.0917, -0.0153, -0.0229,
         -0.0458, -0.0611, -0.0687],
        [-0.0270, -0.0361, -0.0541, -0.0631, -0.0901, -0.1082, -0.0180, -0.0270,
         -0.0541, -0.0721, -0.0811],
        [-0.0041, -0.0055, -0.0083, -0.0097, -0.0138, -0.0166, -0.0028, -0.0041,
         -0.0083, -0.0110, -0.0124],
        [ 0.0165,  0.0219,  0.0329,  0.0384,  0.0549,  0.0658,  0.0110,  0.0165,
          0.0329,  0.0439,  0.0494],
        [ 0.0183,  0.0244,  0.0367,  0.0428,  0.0611,  0.0733,  0.0122,  0.0183,
          0.0367,  0.0489,  0.0550],
        [ 0.0045,  0.0060,  0.0090,  0.0105,  0.0150,  0.0180,  0.0030,  0.0045,
          0.0090,  0.0120,  0.0135],
        [ 0.0056,  0.0075,  0.0112,  0.0131,  0.0187,  0.0225,  0.0037,  0.0056,
          0.0112,  0.0150,  0.0169],
        [ 0.0279,  0.0372,  0.0559,  0.0652,  0.0931,  0.1117,  0.0186,  0.0279,
          0.0559,  0.0745,  0.0838]])
tensor([-0.0076, -0.0090, -0.0014,  0.0055,  0.0061,  0

## Accessing the model parameters

In [33]:
model = nn.Sequential(
  nn.Linear(16, 8),
  nn.Sigmoid(),
  nn.Linear(8, 2))

weight_0 = model[0].weight

bias_1 = model[2].bias

## Updating the weights manually

In [34]:
sample = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])
target = F.one_hot(torch.tensor([2]), 4).double()

model = nn.Sequential(
  nn.Linear(11, 8),
  nn.Linear(8, 6),
  nn.Linear(6, 4)
)

prediction = model(sample)

criterion = nn.CrossEntropyLoss()
loss = criterion(prediction, target)
loss.backward()

weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

lr = 0.001

weight0 = weight0 - lr * grads0
weight1 = weight1 - lr * grads1
weight2 = weight2 - lr * grads2

print(weight0)
print(weight1)
print(weight2)

tensor([[-0.0971,  0.1001,  0.2619,  0.0493,  0.1219,  0.1040,  0.0658,  0.1791,
          0.2696, -0.0118, -0.1172],
        [-0.2400, -0.0057, -0.2672,  0.2262,  0.1076,  0.2741,  0.0531,  0.1012,
          0.0129,  0.0062, -0.1481],
        [ 0.2260, -0.1034, -0.1302, -0.2156, -0.1575,  0.0519, -0.2090, -0.2779,
          0.0301, -0.2071, -0.0193],
        [ 0.1437, -0.0198,  0.2390, -0.1248,  0.1819, -0.2085, -0.0973,  0.2100,
          0.0214, -0.0627, -0.1358],
        [-0.0306, -0.1658, -0.1572,  0.0218,  0.1323, -0.2719,  0.2263, -0.1176,
         -0.1964,  0.1460, -0.0273],
        [ 0.0725,  0.1948, -0.0827,  0.1041, -0.0362,  0.1914, -0.1233, -0.1045,
         -0.0502, -0.1455, -0.0590],
        [-0.1938, -0.2939, -0.2506,  0.1835, -0.1931, -0.2612, -0.1550,  0.1672,
          0.2538,  0.1801,  0.2805],
        [-0.1130, -0.2596,  0.1447,  0.0288,  0.1625,  0.0783, -0.2831, -0.0605,
         -0.0363, -0.1258, -0.1563]], grad_fn=<SubBackward0>)
tensor([[ 0.2667, -0.2727,  0.0

## Using the PyTorch optimizer

In [35]:
optimizer = optim.SGD(model.parameters(), lr=0.001)

optimizer.step()

# Writing your first training loop

## Using the MSELoss

In [36]:
y_hat = np.array(10)
y = np.array(1)

mse_numpy = np.mean((y_hat - y)**2)

criterion = nn.MSELoss()

mse_pytorch = criterion(torch.tensor(y_hat).float(), torch.tensor(y).float())
print(mse_pytorch)

tensor(81.)


## Writing a training loop

In [46]:
features = [[1., 0., 1., 1.], [1., 0., 0., 1.], [1., 0., 1., 1.]]
target = [[0.1099], [0.7500], [0.1636]]

dataset = TensorDataset(torch.Tensor(features).float(), torch.Tensor(target).float())
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

model = nn.Sequential(
  nn.Linear(4, 2),
  nn.Linear(2, 1))

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

num_epochs = 8

for i in range(num_epochs):
  for data in dataloader:
    optimizer.zero_grad()
    feature, target = data
    prediction = model(feature)    
    loss = criterion(prediction, target)    
    loss.backward()
    optimizer.step()

prediction = model(feature)  
print(prediction) 
print(target)    

tensor([[-0.2294],
        [-0.3355],
        [-0.3355]], grad_fn=<AddmmBackward0>)
tensor([[0.7500],
        [0.1099],
        [0.1636]])
