# Running a forward pass

In [11]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

## Building a binary classifier in PyTorch

In [12]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.1244]], grad_fn=<SigmoidBackward0>)


## From regression to multi-class classification

In [13]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.5484, 0.1482, 0.0307, 0.2727]], grad_fn=<SoftmaxBackward0>)


# Using loss functions to assess model predictions

## Creating one-hot encoded labels

In [14]:
y = 1
num_classes = 3

one_hot_numpy = np.array([0, 1, 0])

one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes = num_classes)

print(one_hot_pytorch)

tensor([0, 1, 0])


## Calculating cross entropy loss

In [15]:
y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])
print(one_hot_label)

criterion = nn.CrossEntropyLoss()

loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor([[0, 0, 1, 0]])
tensor(8.0619, dtype=torch.float64)
